spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://chb1:3306/tags_new?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false"
    username: "root"
    password: "123456"
  jpa:
    show-sql: true
    database: MYSQL
  data:
    jpa:
      repositories:
        enabled: true

